#!/bin/bash
# specify the path to the directory of java-files. if the directory is current one, then this line is not needed.
cd IdeaProjects/homework10/src/main/java/ua/com/alevel/planets
filenames=`ls *.java`
for eachfile in $filenames
do
i=0
while read
do
((i++))
done < $eachfile
echo -e "$eachfile -> $i strings"
done

